version: "3.9"
services:
  nginx:
    image: nginx:latest
    profiles:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./nginx/logs:/var/log/nginx
    restart: always
  httpd:
    image: httpd:latest
    profiles:
      - httpd
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro
      - ./certs:/usr/local/apache2/conf/certs:ro
      - ./httpd/logs:/usr/local/apache2/logs
    restart: always